project_id = "xuikcvxwgwqyeulflitn"

[functions.run-manual-query]
verify_jwt = false

[functions.run-ai-journalist]
verify_jwt = false

[functions.backfill-artifact-images]
verify_jwt = false

[functions.analyze-source]
verify_jwt = false

[functions.scheduled-fetch-artifacts]
verify_jwt = false

[functions.scheduled-run-journalism]
verify_jwt = false

[functions.fetch-openrouter-models]
verify_jwt = false
