project_id = "cceprnhnpqnpexmouuig"

[functions.run-ai-journalist]
verify_jwt = false

[functions.process-journalism-queue-item]
verify_jwt = false

[functions.backfill-artifact-images]
verify_jwt = false

[functions.fetch-rss-feeds]
verify_jwt = false

[functions.scheduled-fetch-artifacts]
verify_jwt = false

[functions.scheduled-run-journalism]
verify_jwt = false

[functions.manage-schedule]
verify_jwt = false

[functions.fetch-openrouter-models]
verify_jwt = false

[functions.publish-to-ghost]
verify_jwt = false

[functions.run-ai-editor]
verify_jwt = false

[functions.scheduled-run-editor]
verify_jwt = false

